### ISSUE TITLE
Examples Don't show up

### ISSUE THREAD

**Issue by dsbert** [zircleUI/zircleUI#6] opened 2018-02-21 17:07 UTC
The `iframe` contents for the examples are blank when I view them

https://zircleui.github.io/zircleUI/#/?id=counter

```
<iframe scrolling="no" title="Counter by Zircle" src="//codepen.io/zircle/embed/qpgzqz/?height=450&amp;theme-id=light&amp;default-tab=result&amp;embed-version=2" allowtransparency="true" allowfullscreen="true" style="width: 100%;" height="450" frameborder="no">See the Pen <a href='https://codepen.io/zircle/pen/qpgzqz/'>Counter by Zircle</a>
#document
<html>
<head></head>
<body></body>
</html>
</iframe>
```

**Comment by tinchox5** [comment] 2018-02-21 19:28
Hi @dsbert! I can't reproduce the issue. If I click on any of the tabs like "CSS", "HTML", "JS" or "RESULT" , I can see the code. And, I'm able to go to codepen and edit the example if I click on "Edit on Codepen".
![screen shot 2018-02-21 at 4 23 53 pm](https://user-images.githubusercontent.com/11557901/36500830-213ec196-1724-11e8-96b9-e7c8f3180efe.png)

**Comment by dsbert** [comment] 2018-02-21 20:20
@tinchox5 It looks like Privacy Badger removes the cookie and referrer which prevents Codepen from loading properly.

https://twitter.com/CodePen/status/860237169192914945

**Comment by tinchox5** [comment] 2018-02-21 21:08
Oh, thank you noticed that, I think the best solution may be replace the examples with jsfiddle. What you you think?

**Comment by dsbert** [comment] 2018-02-22 03:39
I don't have much experience with either of those services so I'm not really sure what the best option is.

**Comment by tinchox5** [comment] 2018-02-22 18:35
For now, I close it as it is an issue not related to this project. Thank you

**Closed by tinchox5** 2018-02-22 18:35 UTC
