### ISSUE TITLE
visual error on FF

### ISSUE THREAD

**Issue by einacio** [zircleUI/zircleUI#1] opened 2017-10-30 20:59 UTC
Hi, I'm looking at the demo page with FF developer (57.0b12), and I'm seeing errors on the circles. There are scroll bars.

![zircle](https://user-images.githubusercontent.com/1534114/32195384-e6a24bac-bd9b-11e7-8f39-492e62d1e42e.png)

I see that on the css you have `overflow-y:scroll;` on `.z-content`, don't know if it serves any purpose, but removing it looks better

**Comment by tinchox5** [comment] 2017-10-30 22:09
Thank you for showing me the issue! Apparently thats happens with certain versions of FF. The main purpose of the scroll is show a custom circular scroll when there is a long content in <z-panel>. I’ll try to fix it soon.

**Comment by tinchox5** [comment] 2017-10-31 15:14
@einacio I think the issue is fixed in the new zircle release (zircle@0.1.1)  Do you use FF under Linux?

**Comment by einacio** [comment] 2017-10-31 16:05
it looks fine now.
this is from FF on win.

**Comment by tinchox5** [comment] 2017-10-31 17:42
Thank you @einacio! Also thanks to @maxxsch28 and @mromanuk!

**Closed by tinchox5** 2017-10-31 17:42 UTC
Labels: the first issue
